# SPDX-License-Identifier: Apache-2.0
"""Bounded, service-controlled Agent loop for internal QA workflows."""

from agentic_qa.runtime.qa_harness.context_builder import AuthorizedContextBuilder
from agentic_qa.runtime.qa_harness.contracts import (
    AgentStepResult,
    BudgetSnapshot,
    HarnessContextBlock,
    HarnessEvidenceRef,
    HarnessRunContext,
    HarnessRunResult,
    HarnessRunSpec,
    Observation,
    ObservationUsage,
    SkillIntent,
)
from agentic_qa.runtime.qa_harness.extension_descriptors import (
    ExtensionCompatibilityChecker,
    ExtensionCompatibilityRequirement,
    ExtensionCompatibilityResult,
    ExtensionDependency,
    ExtensionDescriptor,
    ExtensionDescriptorProjector,
    ExtensionHealthStatus,
    ExtensionKind,
    ExtensionLifecycleStatus,
)
from agentic_qa.runtime.qa_harness.evaluation import (
    EvaluationCaseMeasurement,
    EvaluationCaseResult,
    EvaluationFrozenReference,
    EvaluationFrozenSnapshot,
    EvaluationInput,
    MeasurementClass,
    EvaluationMetrics,
    EvaluationResult,
    EvaluationRule,
    EvaluationScopeSnapshot,
    EvaluationTargetReference,
    QaEvaluationRunner,
    SKILL_EVALUATION_METRICS,
    SkillEvaluationMetricComparison,
    SkillEvaluationMetricDefinition,
    SkillEvaluationMetricRegistry,
    SkillEvaluationObservation,
    SkillVersionEvaluationInput,
    SkillVersionEvaluationResult,
    build_evaluation_scope_snapshot,
)
from agentic_qa.runtime.qa_harness.profiles import (
    BuiltinQaProfileCatalog,
    QaProfile,
    QaProfileBudgetDefaults,
    QaProfileExtensionSelection,
    QaProfileRequirement,
    QaProfileResolutionSnapshot,
    QaProfileResolver,
    build_qa_profile,
    qa_profile_hash,
)
from agentic_qa.runtime.qa_harness.runtime import QaHarnessRuntime, ServiceCapabilityError
from agentic_qa.runtime.qa_harness.stop_reasons import HarnessRunState, HarnessRunStatus, StopReason

__all__ = [
    "AgentStepResult",
    "AuthorizedContextBuilder",
    "BudgetSnapshot",
    "BuiltinQaProfileCatalog",
    "ExtensionCompatibilityChecker",
    "ExtensionCompatibilityRequirement",
    "ExtensionCompatibilityResult",
    "ExtensionDependency",
    "ExtensionDescriptor",
    "ExtensionDescriptorProjector",
    "ExtensionHealthStatus",
    "ExtensionKind",
    "ExtensionLifecycleStatus",
    "EvaluationCaseMeasurement",
    "EvaluationCaseResult",
    "EvaluationFrozenReference",
    "EvaluationFrozenSnapshot",
    "EvaluationInput",
    "MeasurementClass",
    "EvaluationMetrics",
    "EvaluationResult",
    "EvaluationRule",
    "EvaluationScopeSnapshot",
    "EvaluationTargetReference",
    "HarnessContextBlock",
    "HarnessEvidenceRef",
    "HarnessRunContext",
    "HarnessRunResult",
    "HarnessRunSpec",
    "HarnessRunState",
    "HarnessRunStatus",
    "Observation",
    "ObservationUsage",
    "QaHarnessRuntime",
    "QaEvaluationRunner",
    "SKILL_EVALUATION_METRICS",
    "SkillEvaluationMetricComparison",
    "SkillEvaluationMetricDefinition",
    "SkillEvaluationMetricRegistry",
    "SkillEvaluationObservation",
    "SkillVersionEvaluationInput",
    "SkillVersionEvaluationResult",
    "QaProfile",
    "QaProfileBudgetDefaults",
    "QaProfileExtensionSelection",
    "QaProfileRequirement",
    "QaProfileResolutionSnapshot",
    "QaProfileResolver",
    "ServiceCapabilityError",
    "SkillIntent",
    "StopReason",
    "build_evaluation_scope_snapshot",
    "build_qa_profile",
    "qa_profile_hash",
]
