# SPDX-License-Identifier: Apache-2.0
from enum import StrEnum


class HarnessRunState(StrEnum):
    ASSEMBLE_CONTEXT = "ASSEMBLE_CONTEXT"
    MODEL_STEP = "MODEL_STEP"
    VALIDATE_AGENT_OUTPUT = "VALIDATE_AGENT_OUTPUT"
    RESOLVE_INTENT = "RESOLVE_INTENT"
    AWAIT_SERVICE_CAPABILITY = "AWAIT_SERVICE_CAPABILITY"
    OBSERVE = "OBSERVE"
    COMPLETE = "COMPLETE"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class HarnessRunStatus(StrEnum):
    COMPLETED = "completed"
    NEEDS_REVIEW = "needs_review"
    DEGRADED = "degraded"
    BLOCKED = "blocked"
    FAILED = "failed"
    CANCELLED = "cancelled"


class StopReason(StrEnum):
    COMPLETED_VALID_RESULT = "COMPLETED_VALID_RESULT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_OUTPUT_INVALID = "MODEL_OUTPUT_INVALID"
    AGENT_OUTPUT_INVALID = "AGENT_OUTPUT_INVALID"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    BINDING_UNAVAILABLE = "BINDING_UNAVAILABLE"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    CANCELLED = "CANCELLED"
    GUARDRAIL_BLOCKED = "GUARDRAIL_BLOCKED"
    SERVICE_CAPABILITY_FAILED = "SERVICE_CAPABILITY_FAILED"
    EXTENSION_POINT_NOT_ALLOWED = "EXTENSION_POINT_NOT_ALLOWED"
    LIFECYCLE_STAGE_UNSUPPORTED = "LIFECYCLE_STAGE_UNSUPPORTED"
    OBSERVATION_INVALID = "OBSERVATION_INVALID"


TERMINAL_SERVICE_REASONS = {
    StopReason.MODEL_UNAVAILABLE,
    StopReason.MODEL_OUTPUT_INVALID,
    StopReason.APPROVAL_REQUIRED,
    StopReason.CAPABILITY_UNAVAILABLE,
    StopReason.BINDING_UNAVAILABLE,
    StopReason.GUARDRAIL_BLOCKED,
    StopReason.SERVICE_CAPABILITY_FAILED,
}
